plugins {
    id "fabric-loom"
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    implementation project(":common")
    compileOnly "org.spongepowered:mixin:0.8.7"
    annotationProcessor "org.spongepowered:mixin:0.8.7"
    annotationProcessor "com.google.guava:guava:32.1.2-jre"
    annotationProcessor "com.google.code.gson:gson:2.8.9"
}

sourceSets {
    main {
        java {
            srcDir project(":common").sourceSets.main.java
        }
        resources {
            srcDir project(":common").sourceSets.main.resources
            exclude "architectury.common.json"
        }
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

remapJar {
    archiveBaseName = "${archives_base_name}-fabric${minecraft_version}"
}

sourcesJar {
    from project(":common").sourceSets.main.allSource
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

jar {
    from project(":common").sourceSets.main.output
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
