org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=true
org.gradle.parallel=true

minecraft_version=1.21.1
archives_base_name=blink
mod_version=4.9.1
maven_group=com.xbodw.blink

# Dependencies
fabric_loader_version=0.16.10
fabric_api_version=0.106.0+1.21.1

neoforge_version=21.1.234

# Fabric Loom version
loom_version=1.10-SNAPSHOT

# NeoGradle version
neogradle_version=7.1.38

# Skip Vineflower decompiler (use binary patch mode instead - faster, less memory)
neogradle.subsystems.decompiler.enabled=false
