org.gradle.jvmargs=-Xmx2048M
org.gradle.daemon=true
org.gradle.parallel=true

# 镜像源配置
systemProp.https.proxyHost=
systemProp.https.proxyPort=
systemProp.http.proxyHost=
systemProp.http.proxyPort=

minecraft_version=1.20.1
enabled_platforms=fabric,forge

archives_base_name=blink
mod_version=4.4.1
maven_group=com.xbodw.blink

architectury_version=9.1.12

fabric_loader_version=0.14.21
fabric_api_version=0.83.0+1.20.1

forge_version=1.20.1-47.2.0



