allprojects {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public/' }
        maven { url 'https://maven.aliyun.com/repository/central/' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin/' }
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
        maven { name = 'FabricMC'; url = 'https://maven.fabricmc.net/' }
        maven { name = 'NeoForge'; url = 'https://maven.neoforged.net/releases/' }
        mavenCentral()
        gradlePluginPortal()
    }
}

settingsEvaluated { settings ->
    settings.pluginManagement {
        repositories {
            maven { url 'https://maven.aliyun.com/repository/gradle-plugin/' }
            maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public/' }
            maven { name = 'FabricMC'; url = 'https://maven.fabricmc.net/' }
            maven { name = 'NeoForge'; url = 'https://maven.neoforged.net/releases/' }
            gradlePluginPortal()
            mavenCentral()
        }
    }
}
