modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0"

[[mods]]
modId = "blink"
version = "${version}"
displayName = "Blink"
authors = "xbodwf"
logoFile = "icon.png"
description = '''
A mod that adds a filler tool to quickly fill regions with blocks!
'''

[[dependencies.blink]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.blink]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "blink.mixins.json"
